table_wooden:
  filename: base_objects/table_wooden.urdf
  position: [-0.26305, -0.04297, -0.45]
  orientation: [0, 0, 0]
table_ikea:
  filename: base_objects/table_ikea.urdf
  position: [0.6114, -0.0502, 0]
  orientation: [3.1214402987334857, 0.0013161004296716216, 0]
back_wall:
  filename: base_objects/back_wall.urdf
  position: [-0.7366, 0, 0]
  orientation: [0, 0, 0]
support_beams:
    filename: base_objects/support_beams.urdf
    position: [-0.045, 0, -0.022225]
    orientation: [0, 0, 0]
clamps:
    filename: base_objects/clamps.urdf
    position: [0.12, 0, -0.066675]
    orientation: [0, 0, 0]
plane:
  filename: base_objects/plane.urdf
  position: [0, 0, -1]
  orientation: [0, 0, 0]
